language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: a0u+j8ie7d6vngObc91aSfsTlFAA5Ccza6kEctXEDaeCHLwtmeN0Jv/QfqVcYQmHoJFuuvJ3xu1aid0f2cI5+d1Tq71L59rw9E8Dtcwpj5qBlC5fSfnnKeelUrN1+wEbfSkUlJeSJWZrDQVApKwrN45gc7if3Q6iNTEgeN9tHCU=
  file:
    - 'speakers.js'
    - 'speakers.min.js'
  on:
    tags: true
